"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pigeon.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False,
 'iconfile': 'pigeon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# py2exe stuff goes here ~~~

#from distutils.core import setup
#import py2exe

#setup(
#	options = {'py2exe': {'compressed': True}},
#    windows = [{'script': "pigeon.py"}],
#    zipfile = None,
#    )
